### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by EiffL** [LSSTISSC/Tidalsaurus#2]
This issue is to document our Goals and TODOs for this project

## Data Preparation
- [x] #3
- [x] #4
- [x] #5

## Model training
- [x] Write down a script that trains and exports a Self-Supervised representation of HSC images
- [ ] (Optional) Fine tune the data augmentation strategy to optimize our ability to find tidal features

## Search for new galaxies of interest
- [ ] Apply trained model to HSC dataset and identify candidates
